RSS_FEEDS = {
    "TechCrunch": "https://techcrunch.com/feed/",
    "The Verge": "https://www.theverge.com/rss/index.xml",
    "Wired": "https://www.wired.com/feed/rss",
    "Ars Technica": "https://feeds.arstechnica.com/arstechnica/index",
    "Engadget": "https://www.engadget.com/rss.xml",
    "CNET": "https://www.cnet.com/rss/all/",
    "MIT Technology Review": "https://www.technologyreview.com/feed/",
    "IEEE Spectrum": "https://spectrum.ieee.org/feeds/feed.rss",
    "ZDNet": "https://www.zdnet.com/news/rss.xml",
    "Computerworld": "https://www.computerworld.com/index.rss",
    "OpenAI News": "https://openai.com/news/rss.xml",
    "Google Research": "https://research.google/blog/rss/",
    "Hugging Face Blog": "https://huggingface.co/blog/feed.xml",
    "NVIDIA Developer": "https://developer.nvidia.com/blog/feed/",
    "KDnuggets": "https://www.kdnuggets.com/feed",
    "Towards Data Science": "https://towardsdatascience.com/feed",
    "InfoQ": "https://www.infoq.com/feed/",
    "InfoWorld": "https://www.infoworld.com/index.rss",
    "GitHub Blog": "https://github.blog/feed/",
    "Stack Overflow Blog": "https://stackoverflow.blog/feed/",
    "Hacker News": "https://news.ycombinator.com/rss",
    "The Hacker News": "https://feeds.feedburner.com/TheHackersNews",
    "Krebs on Security": "https://krebsonsecurity.com/feed/",
    "BleepingComputer": "https://www.bleepingcomputer.com/feed/",
    "AWS News": "https://aws.amazon.com/blogs/aws/feed/",
    "Google Cloud": "https://cloudblog.withgoogle.com/products/rss/",
    "Azure Blog": "https://azure.microsoft.com/en-us/blog/feed/",
    "Docker Blog": "https://www.docker.com/blog/feed/",
    "MacRumors": "https://feeds.macrumors.com/MacRumors-All",
    "9to5Mac": "https://9to5mac.com/feed/",
    "VentureBeat": "https://venturebeat.com/feed/",
    "SiliconANGLE": "https://siliconangle.com/feed/",
}
#hackernews
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"
#reddit
REDDIT_FEEDS = {
    "technology": "https://www.reddit.com/r/technology/new/.rss",
    "programming": "https://www.reddit.com/r/programming/new/.rss",
    "MachineLearning": "https://www.reddit.com/r/MachineLearning/new/.rss",
}

TOPIC_KEYWORDS = {
    "Artificial Intelligence": {
        "artificial intelligence": 5,
        "machine learning": 5,
        "deep learning": 5,
        "neural network": 5,
        "generative ai": 5,
        "llm": 5,
        "large language model": 5,
        "gpt": 5,
        "chatgpt": 5,
        "openai": 5,
        "anthropic": 5,
        "claude": 5,
        "gemini": 5,
        "copilot": 4,
        "cursor": 4,
        "mistral": 4,
        "llama": 4,
        "stable diffusion": 5,
        "midjourney": 4,
        "perplexity": 4,
        "ai agent": 5,
        "agentic ai": 5,
        "rag": 4,
        "fine tuning": 4,
        "embedding": 3,
        "inference": 3,
        "ai": 1,
    },

    "Programming": {
        "programming": 5,
        "software engineering": 5,
        "coding": 3,
        "developer": 3,
        "python": 5,
        "java": 5,
        "javascript": 5,
        "typescript": 5,
        "c++": 5,
        "cpp": 5,
        "c#": 4,
        "go": 4,
        "golang": 4,
        "rust": 5,
        "swift": 4,
        "kotlin": 4,
        "php": 3,
        "ruby": 3,
        "scala": 3,
        "compiler": 3,
        "api": 3,
        "sdk": 3,
        "framework": 3,
    },

    "Web Development": {
        "react": 5,
        "next.js": 5,
        "nextjs": 5,
        "vue": 5,
        "angular": 5,
        "svelte": 5,
        "node.js": 5,
        "nodejs": 5,
        "express": 4,
        "fastapi": 5,
        "django": 5,
        "flask": 4,
        "tailwind": 4,
        "frontend": 4,
        "backend": 4,
        "full stack": 5,
        "graphql": 5,
        "rest api": 4,
    },

    "Cloud Computing": {
        "cloud": 3,
        "aws": 5,
        "amazon web services": 5,
        "azure": 5,
        "gcp": 5,
        "google cloud": 5,
        "docker": 5,
        "kubernetes": 5,
        "terraform": 5,
        "serverless": 4,
        "devops": 4,
        "cloudflare": 4,
        "vercel": 4,
        "netlify": 4,
        "helm": 4,
        "container": 3,
        "containerization": 4,
    },

    "Cybersecurity": {
        "cybersecurity": 5,
        "security": 2,
        "malware": 5,
        "ransomware": 5,
        "phishing": 5,
        "breach": 5,
        "data breach": 5,
        "vulnerability": 5,
        "exploit": 5,
        "zero-day": 5,
        "0-day": 5,
        "patch": 4,
        "patches": 4,
        "security update": 4,
        "cve": 5,
        "hack": 2,
        "hacker": 3,
        "cyber attack": 5,
        "encryption": 4,
    },

    "Hardware": {
        "gpu": 5,
        "cpu": 5,
        "processor": 5,
        "chip": 4,
        "chipset": 4,
        "nvidia": 5,
        "amd": 5,
        "intel": 5,
        "qualcomm": 5,
        "mediatek": 4,
        "arm": 4,
        "rtx": 5,
        "geforce": 5,
        "radeon": 5,
        "ryzen": 5,
        "xeon": 4,
        "threadripper": 4,
        "cuda": 5,
        "semiconductor": 5,
    },

    "Mobile": {
        "android": 5,
        "ios": 5,
        "iphone": 5,
        "ipad": 4,
        "smartphone": 4,
        "mobile": 3,
        "pixel": 4,
        "galaxy": 4,
        "oneplus": 4,
        "xiaomi": 4,
    },

    "Gaming": {
        "gaming": 5,
        "game": 2,
        "steam": 5,
        "epic games": 5,
        "playstation": 5,
        "ps5": 5,
        "xbox": 5,
        "nintendo": 5,
        "switch": 5,
        "esports": 4,
        "unreal engine": 4,
        "unity": 4,
    },

    "Startups": {
        "startup": 5,
        "funding": 4,
        "seed funding": 5,
        "series a": 5,
        "series b": 5,
        "series c": 5,
        "venture capital": 5,
        "vc": 3,
        "acquisition": 4,
        "merger": 4,
        "ipo": 5,
        "unicorn": 5,
    },

    "Open Source": {
        "open source": 5,
        "linux": 5,
        "github": 5,
        "gitlab": 4,
        "apache": 4,
        "mozilla": 4,
        "gnu": 4,
        "kernel": 4,
        "opensource": 5,
    },

    "Consumer Tech": {
        "apple": 5,
        "google": 5,
        "meta": 5,
        "microsoft": 5,
        "amazon": 5,
        "tesla": 4,
        "spotify": 4,
        "netflix": 4,
        "samsung": 5,
        "macbook": 5,
        "airpods": 4,
        "apple watch": 4,
        "wear os": 4,
        "watchos": 4,
    },

    "Data Science": {
        "data science": 5,
        "data analysis": 4,
        "analytics": 4,
        "etl": 5,
        "data pipeline": 5,
        "big data": 5,
        "spark": 5,
        "hadoop": 5,
        "airflow": 5,
        "pandas": 5,
        "numpy": 5,
        "scikit-learn": 5,
        "jupyter": 4,
    },

    "Databases": {
        "database": 4,
        "sql": 5,
        "mysql": 5,
        "postgres": 5,
        "postgresql": 5,
        "sqlite": 4,
        "mongodb": 5,
        "redis": 5,
        "elasticsearch": 5,
        "cassandra": 4,
        "firebase": 4,
        "supabase": 4,
    },

    "Blockchain": {
        "blockchain": 5,
        "bitcoin": 5,
        "ethereum": 5,
        "crypto": 4,
        "cryptocurrency": 5,
        "web3": 5,
        "nft": 4,
        "smart contract": 5,
        "defi": 5,
        "solana": 5,
    },

    "Space": {
        "space": 3,
        "nasa": 5,
        "spacex": 5,
        "blue origin": 5,
        "starlink": 5,
        "rocket": 4,
        "satellite": 4,
        "mars": 4,
        "moon": 3,
    },

    "Robotics": {
        "robotics": 5,
        "robot": 4,
        "automation": 4,
        "autonomous": 4,
        "drone": 4,
        "humanoid": 5,
        "optimus": 5,
        "tesla bot": 5,
    },

    "Quantum Computing": {
        "quantum computing": 5,
        "quantum": 4,
        "qubit": 5,
        "ibm quantum": 5,
        "google quantum": 5,
        "quantum processor": 5,
    },

    "Networking": {
        "5g": 5,
        "6g": 5,
        "wifi": 4,
        "ethernet": 3,
        "router": 3,
        "network": 3,
        "network security": 5,
        "cisco": 5,
    },

    "AR/VR": {
        "augmented reality": 5,
        "virtual reality": 5,
        "mixed reality": 5,
        "vr": 4,
        "ar": 4,
        "vision pro": 5,
        "meta quest": 5,
    },

    "Internet of Things": {
        "internet of things": 5,
        "iot": 5,
        "smart home": 5,
        "wearable": 4,
        "wearables": 4,
        "embedded": 4,
        "sensor": 3,
        "raspberry pi": 4,
    },

    "Electric Vehicles": {
        "electric vehicle": 5,
        "electric vehicles": 5,
        "ev": 4,
        "tesla": 5,
        "rivian": 5,
        "lucid": 4,
        "battery": 3,
        "charging": 3,
        "autonomous driving": 5,
    },

    "Business": {
        "earnings": 5,
        "revenue": 4,
        "profit": 4,
        "market": 3,
        "stock": 4,
        "ipo": 5,
        "layoffs": 5,
        "merger": 5,
        "acquisition": 5,
        "investment": 4,
    },

    "Science": {
        "science": 3,
        "research": 3,
        "breakthrough": 3,
        "laboratory": 2,
        "nature": 3,
        "scientist": 3,
    },
}

